{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.createSecrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end -}}
{{- end }}
