name: Build OSS Docker Images Without Publishing

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-dockerbuild
      - v[0-9]+.[0-9]+.[0-9]+rc[0-9]+-dockerbuild

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - name: Clone fiftyone
        uses: actions/checkout@v4

      - name: Set Env Vars
        run: |
          echo "today=$(date +%Y%m%d)" >> "$GITHUB_ENV"
          echo "fo_version=${{ github.ref_name }}" >> "$GITHUB_ENV"
          echo "pyver=${{ matrix.python }}" >> "$GITHUB_ENV"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.RW_DOCKERHUB_USER }}
          password: ${{ secrets.RW_DOCKERHUB_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (not latest)
        if: matrix.python != '3.11'
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BUILD_TYPE=released
            FO_VERSION=${{ env.fo_version }}
            PYTHON_VERSION=${{ env.pyver }}
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            voxel51/fiftyone:${{ env.fo_version }}-python${{ env.pyver }}
            voxel51/fiftyone:${{ env.fo_version }}-python${{ env.pyver }}-${{ env.today }}

      - name: Build and push (latest)
        if: matrix.python == '3.11'
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BUILD_TYPE=released
            FO_VERSION=${fo_version}
            PYTHON_VERSION=${pyver}
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            voxel51/fiftyone:${{ env.fo_version }}-python${{ env.pyver }}
            voxel51/fiftyone:${{ env.fo_version }}-python${{ env.pyver }}-${{ env.today }}
            latest
